### ISSUE TITLE
Can't use version 3.1

### ISSUE THREAD

**Issue by SleepyMode** [go-gl/gl#106]
It doesn't let me use go get on version 3.1

```
C:\Users\█████\go\src\███>go get -u github.com/go-gl/gl/v3.1/gles2
# github.com/go-gl/gl/v3.1/gles2
..\github.com\go-gl\gl\v3.1\gles2\package.go:35:11: fatal error: KHR/khrplatform.h: No such file or directory
 // #include <KHR/khrplatform.h>
           ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Velocity-** [comment]
Had the same thing as you, this fixed it for me on Ubuntu:
`sudo apt-get install libgles2-mesa-dev`

**Comment by pwaller** [comment]
I'm going to close this one since there were no further updates, I assume the solution presented by @Velocity- fixed things.
