### ISSUE TITLE
Resizing window does not adjust relative coordinates

### ISSUE THREAD

**Issue by drakbar** [go-gl/gl#119]
So I have a simple triangle geometry like so
```go
+0.0, +0.5, +0.0, // Top
+0.5, -0.5, +0.0,  // Bottom Right
-0.5, -0.5, +0.0,   // Bottom Left
```
When I first run the program the shape is render as expected.
![n](https://user-images.githubusercontent.com/20728117/62955917-8506f000-bdb7-11e9-9cce-3d5599951b7f.png)

However when I resize the window by either the width or height it appears the origin is no longer centered in the window.

![w](https://user-images.githubusercontent.com/20728117/62956021-bd0e3300-bdb7-11e9-8436-ff9dbc0d6b8f.png)
![h](https://user-images.githubusercontent.com/20728117/62956026-bf708d00-bdb7-11e9-918c-32b1777f1ef3.png)

I expect that the triangle should stay centered in the screen, as the geometry is specified in relative coordinates.
 
I am not sure what is causing the observed behavior,  gl or glfw. Any suggestions as to what is causing this?

**Comment by jeff-emanuel** [comment]
You likely are not updating your viewport  on resize.

**Comment by drakbar** [comment]
@jeff-emanuel Thanks, you were right. I have never used glfw to create a window, and I didn't know that you would need to set up that up also.
