### ISSUE TITLE
SIGSEGV: segmentation violation error while running simple example

### ISSUE THREAD

**Issue by IvanGL** [go-gl/gl#12]
Hello

Here is my simple program

	package main

	import (
		gl "github.com/go-gl/gl/v3.3-compatibility/gl"
		glfw "github.com/go-gl/glfw/v3.1/glfw"
		"runtime"
	)

	func main() {
		runtime.LockOSThread()

		err := glfw.Init()
		if err != nil {
			panic(err)
		}
		defer glfw.Terminate()

		window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
		if err != nil {
			panic(err)
		}

		var vxo uint32
		gl.GenVertexArrays(1, &vxo)
		gl.BindVertexArray(vxo)

		window.MakeContextCurrent()

		window.SetInputMode(glfw.StickyKeysMode, glfw.True)

		for !window.ShouldClose() {
			// Do OpenGL stuff
			window.SwapBuffers()
			glfw.PollEvents()
		}
		window.Destroy()
	}

It successfully builds, but I get error when trying to run it:

	user@localhost:~/go/src/g01/test$ ./test
	SIGSEGV: segmentation violation
	PC=0x0
	signal arrived during cgo execution
	
	runtime.cgocall(0x444a20, 0x7f8eb6527ec8)
		/usr/lib/go/src/pkg/runtime/cgocall.c:149 +0x11b fp=0x7f8eb6527eb0
	github.com/go-gl/gl/v3.3-compatibility/gl._Cfunc_glowGenVertexArrays(0x0, 0x1, 0xc210000060)
		github.com/go-gl/gl/v3.3-compatibility/gl/_obj/_cgo_defun.c:5901 +0x31 fp=0x7f8eb6527ec8
	github.com/go-gl/gl/v3.3-compatibility/gl.GenVertexArrays(0x1, 0xc210000060)
		/home/user/go/src/github.com/go-gl/gl/v3.3-compatibility/gl/package.go:21064 +0x3c fp=0x7f8eb6527ee8
	main.main()
		/home/user/go/src/g01/test/main.go:28 +0x115 fp=0x7f8eb6527f48
	runtime.main()
		/usr/lib/go/src/pkg/runtime/proc.c:220 +0x11f fp=0x7f8eb6527fa0
	runtime.goexit()
		/usr/lib/go/src/pkg/runtime/proc.c:1394 fp=0x7f8eb6527fa8
	
	goroutine 3 [syscall]:
	runtime.goexit()
		/usr/lib/go/src/pkg/runtime/proc.c:1394
	
	rax     0x0
	rbx     0x7f8eb6527ec8
	rcx     0x7f8eb6527ec8
	rdx     0x7f8eb6527e60
	rdi     0x1
	rsi     0xc210000060
	rbp     0x8513e0
	rsp     0x7fff25e61678
	r8      0xc210001120
	r9      0x7f8eb6527e60
	r10     0x61
	r11     0x3
	r12     0x525e00
	r13     0x7fff25e617d0
	r14     0x0
	r15     0x0
	rip     0x0
	rflags  0x10202
	cs      0x33
	fs      0x0
	gs      0x0
	
	exit status 2

What is wrong with it?

Here is some details about my environment:

	user@localhost:~/go/src/g01/test$ uname -a
	Linux localhost 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
	user@localhost:~/go/src/g01/test$ go version
	go version go1.2.1 linux/amd64

Thanks.

**Comment by tapir** [comment]
Hi, you should init the GL library as stated in the readme before making any calls.

```go
    if err := gl.Init(); err != nil {
        panic(err)
    }
```

**Comment by IvanGL** [comment]
@tapir My fault, I missed it. Works like a charm . Thank you very much!

**Comment by tapir** [comment]
It's also a good idea to tell GLFW about the GL context you need before creating the window.
```go
glfw.WindowHint(glfw.ContextVersionMajor, 3)
glfw.WindowHint(glfw.ContextVersionMinor, 3)
glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCompatProfile)
```
