### ISSUE TITLE
Why `UniformMatrix3fv` accepts only a *float32?

### ISSUE THREAD

**Issue by Inkeliz** [go-gl/gl#121]
First, I don't understand OpenGL to much, I'm learning about it. 

There's a function `UniformMatrix3fv`:

```
func UniformMatrix3fv(location int32, count int32, transpose bool, value *float32) {
	C.glowUniformMatrix3fv(gpUniformMatrix3fv, (C.GLint)(location), (C.GLsizei)(count), (C.GLboolean)(boolToInt(transpose)), (*C.GLfloat)(unsafe.Pointer(value)))
}
```

However, that function is supposed to accept a array, as a value of `value`, as [described here](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix). I think there's no diference between WebGL and OpenGL.

-------

But the current `UniformMatrix3fv` accepts `*float32`, not a `[]float32`. What `value` is supposed to supply? If I use `&myarray[0]` is enough?

**Comment by jeff-emanuel** [comment]
Yes, pass &myarray[0].  OpenGL is not WebGL.  See
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glUniform.xhtml
 instead.
