### ISSUE TITLE
How to make gl run in more goroutines?

### ISSUE THREAD

**Issue by nzlov** [go-gl/gl#13]

**Comment by jteeuwen** [comment]
If you could be a bit more specific, we might be able to help.

OpenGL requires that all draw calls occur in the same thread/goroutine in which the context was created.

This is a limitation of OpenGL, not Go and is unfortunately not something we can fix. You can create as many goroutines as you wish in your application for all the other logic. Just make sure that any gl call happens in the context thread/routine.

Having said that, the opcoming replacement for OpenGL, called 'Vulkan'(1)(2) has been designed from the ground up to be multi-threaded, so when it is released and ready for use, you may have better luck with it.

(1): https://www.khronos.org/vulkan
(2): https://www.youtube.com/watch?v=qKbtrVEhaw8

**Comment by nzlov** [comment]
Thank you, I get it.
