### ISSUE TITLE
Add link to legacy project to the top of readme please

### ISSUE THREAD

**Issue by kreshikhin** [go-gl/gl#15]
Previous project was developed 5 years. It's not right when anybody just replaces the repository and makes no reference.

Please add link to 
https://github.com/go-gl-legacy/gl

**Comment by joonazan** [comment]
Thank you for the link.
Can we have methods on types like there were in the old version? I don't think they reduce performance significantly. Is there some reason for not having them as an alternative to the API-mirroring functions?

**Comment by shurcooL** [comment]
> Is there some reason for not having them as an alternative to the API-mirroring functions?

These gl bindings are generated using [`glow` binding generator](https://github.com/go-gl/glow). The reason will be a part of that repo, so feel free to take a look.

I know that the [`golang.org/x/mobile/gl`](https://godoc.org/golang.org/x/mobile/gl), [`github.com/goxjs/gl`](https://godoc.org/github.com/goxjs/gl) packages (they have the same API and can be used interchangeably) use methods on  types style of API, so perhaps you'd want to check them out.

**Comment by pwaller** [comment]
Sorry for the breakage. This is now quite old and I guess the majority of people are using the new bindings, so closing.
