### ISSUE TITLE
Not able to import

### ISSUE THREAD

**Issue by Nabhay** [go-gl/gl#161]
The error provided is: go: github.com/go-gl/gl/v3.3/gl@v0.0.0-20231021071112-07e5d0ea2e71: invalid version: missing github.com/go-gl/gl/v3.3/gl/go.mod at revision 07e5d0ea2e71

**Comment by dmitshur** [comment]
There's no package with the import path `github.com/go-gl/gl/v3.3/gl`, so an error is expected.

There are packages with the following import paths:

- [`github.com/go-gl/gl/v3.3-core/gl`](https://pkg.go.dev/github.com/go-gl/gl/v3.3-core/gl)
- [`github.com/go-gl/gl/v3.3-compatibility/gl`](https://pkg.go.dev/github.com/go-gl/gl/v3.3-compatibility/gl)

See https://github.com/go-gl/gl#usage.

**Comment by Nabhay** [comment]
The issue persists, even after reinstalling Go and installing C and using the correct import paths

**Comment by dmitshur** [comment]
What was the exact command you ran, and what was its output?

**Comment by Nabhay** [comment]
```
import (
	"github.com/go-gl/gl/v3.3-core/gl"
	"fmt"
)
```

This is what I used, and it said broken import, no go.mod files found
