### ISSUE TITLE
v2.1: gl.GetProgramiv possibly missing?

### ISSUE THREAD

**Issue by szabba** [go-gl/gl#17]
[The docs](https://godoc.org/github.com/go-gl/gl/v2.1/gl) list no function in direct correspondence with the C API [`glGetProgramiv`](https://www.opengl.org/sdk/docs/man2/xhtml/glGetProgram.xml) function, which I'd expect to use to get the `gl.LINK_STATUS`.

Is this ommision accidental? Or should I do this using some different function? If so, why?

**Comment by shurcooL** [comment]
> [The docs](https://godoc.org/github.com/go-gl/gl/v2.1/gl) list no function in direct correspondence with the C API [`glGetProgramiv`](https://www.opengl.org/sdk/docs/man2/xhtml/glGetProgram.xml) function

They do.

https://godoc.org/github.com/go-gl/gl/v2.1/gl#GetProgramiv

**Comment by szabba** [comment]
Ok, silly me. Sorry for the false alarm.

**Comment by shurcooL** [comment]
No problem! :)
