### ISSUE TITLE
invalid use of unsafe.Pointer

### ISSUE THREAD

**Issue by Wessie** [go-gl/gl#18]
The following code https://github.com/go-gl/gl/blob/master/v3.3-core/gl/conversions.go#L42-47 is invalid because it puts a non-pointer value into a pointer-type, if the GC finds this non-pointer it will crash the program, as can be demonstrated by forcing a GC run while the return value is live https://play.golang.org/p/XslLV2Vpqk

**Comment by shurcooL** [comment]
I think this is somewhat related to https://github.com/go-gl/glow/issues/11, but possibly an easier problem to fix.

Thanks for the reproducible sample code.

**Comment by Wessie** [comment]
taking a look through the glow issue list, this is actually the same as https://github.com/go-gl/glfw/issues/78, I probably should've filed it under that repository instead.
