### ISSUE TITLE
gl.Ptr() clarification in Readme

### ISSUE THREAD

**Issue by mbertschler** [go-gl/gl#22]
I don't really understand how the `gl.Ptr()` function works. The API has a lot of functions that take a `*uint32` to return multiple things, but in the examples always only one thing is returned.

`GenTextures()` takes the number of textures and a `*uint32`. For one texture this is pretty straightforward.

    var texture uint32
    gl.GenTextures(1, &texture)

But how do i have to use `Ptr()` and `GenTextures()` to generate multiple textures?

    var textures = []uin32{ 0, 0, 0 }
    gl.GenTextures(3, ???)

I think a little example for this usecase could help noobs like me to use the package correctly.
Thank you!

**Comment by shurcooL** [comment]
This is a good question. I have actually never seen any examples of code where `gl.GenTextures` is used with the first parameter value other than 1, and I've tried looking though all examples I could find.

`gl.Ptr` is documented as follows:

> Ptr takes a slice or pointer (to a singular scalar value or the first element of an array or slice) and returns its GL-compatible address.

I would try the following and see if it works:

```Go
var textures = make([]uint32, 3)
gl.GenTextures(len(textures), gl.Ptr(textures))
```

Since `textures` in the above snippet is a slice, I think it should work. But you should test and see.

**Comment by mbertschler** [comment]
I got it to work like this:
```go
var textures = make([]uint32, 3)
gl.GenTextures(3, (*uint32)(gl.Ptr(textures)))
```
When I ported an app from the old `go-gl/gl` to the new package the biggest confusions came from the Go/C type conversions. It took me some time to figure out things like that Str() doesn't null-terminate the strings for me. But this was even weirder:
```go 
var (
	status    int32
	logLength int32
	infoLog   []byte
)
gl.GetShaderiv(VertexShader, gl.COMPILE_STATUS, &status)
if status != 1 {
	gl.GetShaderiv(VertexShader, gl.INFO_LOG_LENGTH, &logLength)
	infoLog = make([]byte, logLength)
	
	gl.GetShaderInfoLog(VertexShader, logLength, nil, (*uint8)(gl.Ptr(infoLog)))
	log.Println("Vertex shader:", string(infoLog))
	os.Exit(1)
}
```
At least it works now, thank you!
