### ISSUE TITLE
signal arrived during cgo execution

### ISSUE THREAD

**Issue by nzlov** [go-gl/gl#24]
os :windows 10
arch: amd64

go version : go1.4.2

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during cgo execution

github.com/go-gl/gl/all-core/gl._Cfunc_glowCreateProgram(0x0, 0x0)
        github.com/go-gl/gl/all-core/gl/_obj/_cgo_gotypes.go:3729 +0x4a
github.com/go-gl/gl/all-core/gl.CreateProgram(0x4e83b2)
        d:/workspace/src/github.com/go-gl/gl/all-core/gl/package.go:9314 +0x31
github.com/mandroa/desktop/gl.GL20.CreateProgram(0xc000000000)
        d:/workspace/src/github.com/mandroa/desktop/gl/gl20.go:113 +0x2e
github.com/mandroa/desktop/gl.(*GL20).CreateProgram(0x94adf8, 0x0)
        <autogenerated>:26 +0xa7
github.com/mandroa/graphics/gl/glut.CreateProgram(0x6ca930, 0x14a, 0x6ca810, 0x105, 0xc000000000, 0x
0, 0x0)
        d:/workspace/src/github.com/mandroa/graphics/gl/glut/glut.go:8 +0x67
github.com/mandroa/m2d.NewBatchFromSize(0x3e8, 0xc08204c090)
        d:/workspace/src/github.com/mandroa/m2d/batch.go:49 +0x98
github.com/mandroa/m2d.NewBatch(0x607a40)
        d:/workspace/src/github.com/mandroa/m2d/batch.go:43 +0x2e
github.com/mandroa/examples/flappy/code.(*loadscreen).Show(0xc082005860)
        d:/workspace/src/github.com/mandroa/examples/flappy/code/game.go:28 +0x53
github.com/mandroa/application.(*Game).SetScreen(0xc082002b60, 0x10b2558, 0xc082005860)
        d:/workspace/src/github.com/mandroa/application/game.go:33 +0xbc
github.com/mandroa/examples/flappy/code.(*Game).Create(0xc082002b60)
        d:/workspace/src/github.com/mandroa/examples/flappy/code/game.go:17 +0xb3
github.com/mandroa/desktop.(*Application).init(0xc08200a3c0)
        d:/workspace/src/github.com/mandroa/desktop/application.go:119 +0x999
github.com/mandroa/desktop.NewApplication(0x10b23d0, 0xc082002b60, 0xc082068000)
        d:/workspace/src/github.com/mandroa/desktop/application.go:38 +0xdd
github.com/mandroa/runtime.Run(0x10b23d0, 0xc082002b60, 0xc082068000)
        d:/workspace/src/github.com/mandroa/runtime/run_windows.go:11 +0x43
main.main()
        D:/workspace/src/github.com/mandroa/examples/flappy/main.go:18 +0xc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        D:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive, locked to thread]:
azul3d.org/native/al%2ev1.dispatcher()
        d:/workspace/src/azul3d.org/native/al.v1/dispatcher.go:29 +0x6f
created by azul3d.org/native/al%2ev1.init路1
        d:/workspace/src/azul3d.org/native/al.v1/dispatcher.go:20 +0x2c
rax     0xc08205a000
rbx     0xc082059a70
rcx     0x94b200
rdx     0xc082059a18
rdi     0xc08205a000
rsi     0x93fdc0
rbp     0x940180
rsp     0x24fe78
r8      0xc082018000
r9      0xc082059a18
r10     0xa0
r11     0x617c40
r12     0x0
r13     0x0
r14     0x280
r15     0x10
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
AL lib: (EE) alc_cleanup: 1 device not closed
exit status 2

**Comment by shurcooL** [comment]
The more important line is `PC=0x0`, which suggests a null pointer being dereferenced.

Did you make sure to call [`gl.Init()`](http://godoc.org/github.com/go-gl/gl/all-core/gl#Init)?

**Comment by nzlov** [comment]
```
import ggl "github.com/go-gl/gl/all-core/gl"

func init() {
	if err := ggl.Init(); err != nil {
		panic(err)
	}

	gl.MGL20 = &GL20{}
}

```

**Comment by nzlov** [comment]
mac linux is ok,only windows...

**Comment by shurcooL** [comment]
Can you try one of the samples that are known to work, e.g., `go get -u github.com/go-gl/examples/glfw31-gl21-cube`, and see if that works for you?

https://github.com/go-gl/examples/tree/master/glfw31-gl21-cube

**Comment by shurcooL** [comment]
> mac linux is ok,only windows...

I think I recognize the problem. This is a guess, I think on Windows you need to call `gl.Init` after a window has been created and its OpenGL context was made current. You can't do it before. Try that.

If this guess is right, then the example I mentioned above should work, since it calls `gl.Init` after creating a window and making its context current.

**Comment by nzlov** [comment]
`go get -u github.com/go-gl/examples/glfw31-gl21-cube` is ok,thx!

**Comment by tapir** [comment]
Looks like a good entry for the README
