### ISSUE TITLE
functions defined in versions that dont support them

### ISSUE THREAD

**Issue by splace** [go-gl/gl#27]
just been trying to get any ProgramUniform** to work, only to eventually discover they aren’t supported in Opengl version 2.1, but are defined, and don't throw any warning in  "gl/V2.1/gl/package.go"

**Comment by shurcooL** [comment]
OpenGL has the notion of extensions that can implement additional functionality that is not a part of the core API. Many video card drivers expose extensions that allow additions.

However, I'm not sure if that applies here. We need to look into it.

**Comment by shurcooL** [comment]
Hmm, this is quite strange.

I'm seeing that `v2.1/gl` package contains more than 2x the funcs of `all-core`. I would expect `all-core` to be much larger.

```
$ godoc github.com/go-gl/gl/v2.1/gl | grep '^func' | wc -l
    2649
$ godoc github.com/go-gl/gl/all-core/gl | grep '^func' | wc -l
    1292
```

Did we inadvertently swap the two?

(It wouldn't resolve this issue as `all-core` also contains `ProgramUniform` funcs.)

**Comment by shurcooL** [comment]
The `go generate` parameters [look okay](https://github.com/go-gl/gl/blob/41aed3351edcf3da1ccc41c8a1db99af2c854ea7/generate.go#L3-L4). So if this is an issue, it would be in `glow`.

**Comment by errcw** [comment]
I believe the inclusion of the `ProgramUniform` functions in v2.1 is "correct" insofar as our prebuilt version of v2.1 is inclusive of all compatible extensions, including `GL_ARB_separate_shader_objects` because it is compatible with API "gl", and that extension contains all the `ProgramUniform*` functions.

I think all-core contains fewer functions because it specifies the core profile which [restricts the extensions we include](https://github.com/go-gl/glow/blob/master/spec.go#L448) to only those defined as compatible with `glcore` which in turn excludes extensions such as `GL_AMD_depth_clamp_separate`.

Thus overall I believe this is working as intended, if not working intuitively. We might reconsider our extension inclusion policy.

**Comment by splace** [comment]
i wonder if this has happened essentially because profiles didn't come in till 3.0.

but then in a way didn't opengl ES take over this area, with its profiling system, so something like ES 2.0 common profile might fix this nicely.

do you intend to have ES available?

**Comment by shurcooL** [comment]
> I think all-core contains fewer functions because it specifies the core profile which [restricts the extensions we include](https://github.com/go-gl/glow/blob/master/spec.go#L448) to only those defined as compatible with `glcore` which in turn excludes extensions such as `GL_AMD_depth_clamp_separate`.

That was what I suspected, and it makes sense. Thanks for the explanation.

**Comment by shurcooL** [comment]
> Thus overall I believe this is working as intended, if not working intuitively.

I agree. I think this issue can be closed.

> i wonder if this has happened essentially because profiles didn't come in till 3.0.

Yep, 2.1 has no notion of profiles.

> do you intend to have ES available?

[glow bindings generator](https://github.com/go-gl/glow) is capable of generated bindings for OpenGL ES as far as I know, but for some reason we didn't include pre-generated ones in this repo.

If you're looking to use OpenGL ES API, you may consider using these alternative libraries that expose OpenGL-like universal API that work on more platforms:

- [`golang.org/x/mobile/gl`](https://godoc.org/golang.org/x/mobile/gl) - OpenGL ES-like API with support for mobile (iOS, Android) and desktop (OS X, Linux).
- [`github.com/goxjs/gl`](https://godoc.org/github.com/goxjs/gl) - OpenGL ES-like API with support for desktop (OS X, Linux, Windows), mobile (iOS, Android, but older version) and browser.

**Comment by splace** [comment]
thanks for the response, i see more clearly now.

but thinking about it might be cool if the extensions were grouped into another file, say "package-extensions.go"
