### ISSUE TITLE
example of glMapBuffer?

### ISSUE THREAD

**Issue by Triangle345** [go-gl/gl#28]
I was wondering if someone can give an example of glMapBuffer:

https://www.opengl.org/sdk/docs/man/html/glMapBuffer.xhtml

As this returns an "Unsafe pointer". I was wondering how one would go copying a slice into a memory mapped vbo or something?

**Comment by shurcooL** [comment]
That's a good question. Unfortunately, I am not aware of any current examples and I haven't used it myself yet.

**Comment by thinkofdeath** [comment]
I've wrapped the call with this https://github.com/thinkofdeath/steven/blob/master/render/gl/buffer.go#L93-L109 in my code so it returns a byte slice but it does require you to know the size of the returned buffer.

**Comment by pwaller** [comment]
I guess this is resolved. If not not please ping the thread or reopen or open a new issue.

**Comment by shurcooL** [comment]
> I was wondering if someone can give an example of glMapBuffer

I was going to suggest looking for use examples on Sourcegraph:

https://sourcegraph.com/github.com/go-gl/gl/-/info/GoPackage/github.com/go-gl/gl/v2.1/gl/-/MapBuffer

But unfortunately it seems there are no indexed usages of `gl.MapBuffer` in the wild right now.
