### ISSUE TITLE
blank screen when it should be a triangle

### ISSUE THREAD

**Issue by sharpner** [go-gl/gl#3]
Hello! 

Im trying to grasp the restructuring of your go-gl library. But I'm having problems drawing a simple triangle with the new opengl4 bindings.

Maybe I'm doing something wrong, but it could also be a bug, any help would be appreciated! 

The code:

```Go
package main

import (
	"fmt"
	"runtime"

	gl "github.com/go-gl/gl/v4.1-core/gl"
	glfw "github.com/go-gl/glfw/v3.1/glfw"
)

var points = []float32{
	0.0, 0.5, 0.0,
	0.5, -0.5, 0.0,
	-0.5, -0.5, 0.0,
}

var vertexShader = `
#version 410

in vec3 vp;
void main() {
gl_Position = vec4(vp, 1.0);
}
` + "\x00"

var fragmentShader = `
#version 410

out vec4 frag_colour;
void main() {
frag_colour = vec4(0.5, 0.0, 0.5, 1.0);
}
` + "\x00"

func main() {
	runtime.LockOSThread()

	if err := glfw.Init(); err != nil {
		panic(err)
	}

	glfw.WindowHint(glfw.ContextVersionMajor, 4)
	glfw.WindowHint(glfw.ContextVersionMinor, 1)
	glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)    // Necessary for OS X
	glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCoreProfile) // Necessary for OS X
	glfw.WindowHint(glfw.OpenGLDebugContext, glfw.True)

	glfw.WindowHint(glfw.Resizable, glfw.True)

	win, err := glfw.CreateWindow(800, 600, "Tutorial #1", nil, nil)

	if err != nil {
		panic(err)
	}

	if err := gl.Init(); err != nil {
		panic(err)
	}

	win.MakeContextCurrent()
	gl.ClearColor(1.0, 1.0, 1.0, 1.0)

	gl.Enable(gl.DEPTH_TEST)
	gl.DepthFunc(gl.LESS)

	fmt.Printf("%s\n", gl.GoStr(gl.GetString(gl.RENDERER)))
	fmt.Printf("%s\n", gl.GoStr(gl.GetString(gl.VERSION)))

	var vbo uint32
	gl.GenBuffers(1, &vbo)
	gl.BindBuffer(gl.ARRAY_BUFFER, vbo)
	gl.BufferData(gl.ARRAY_BUFFER, len(points)*4, gl.Ptr(&points), gl.STATIC_DRAW)

	var vao uint32
	gl.GenVertexArrays(1, &vao)
	gl.BindVertexArray(vao)
	gl.EnableVertexAttribArray(0)
	gl.BindBuffer(gl.ARRAY_BUFFER, vbo)
	gl.VertexAttribPointer(0, 3, gl.FLOAT, false, 0, nil)
	gl.Viewport(0, 0, 800, 600)

	shader := createProgram()

	for !win.ShouldClose() {
		gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)

		gl.UseProgram(shader)
		gl.BindVertexArray(vao)
		gl.DrawArrays(gl.TRIANGLES, 0, 3)

		glfw.PollEvents()
		win.SwapBuffers()
	}
}

func createProgram() uint32 {
	vs := gl.CreateShader(gl.VERTEX_SHADER)
	cvertexShader := gl.Str(vertexShader)
	gl.ShaderSource(vs, 1, &cvertexShader, nil)
	gl.CompileShader(vs)

	fs := gl.CreateShader(gl.FRAGMENT_SHADER)
	cfragmentShader := gl.Str(fragmentShader)
	gl.ShaderSource(fs, 1, &cfragmentShader, nil)
	gl.CompileShader(fs)

	shaderProgram := gl.CreateProgram()
	gl.AttachShader(shaderProgram, fs)
	gl.AttachShader(shaderProgram, vs)

	gl.LinkProgram(shaderProgram)

	return shaderProgram
}
```

**Comment by sharpner** [comment]
Setting GlewExperimental might help, any documentation on how to enable it?

**Comment by shurcooL** [comment]
`gl.Ptr(&points)` is incorrect. `gl.Ptr` needs a slice or pointer to element. Not pointer to slice.

So it should be either `gl.Ptr(points)` (since it's already a slice) or `gl.Ptr(&points[0])`.

We may want to improve docs for `gl.Ptr`. Also related to #2.

**Comment by sharpner** [comment]
thank you very much. gl.Ptr(&points[0]) is the way to go. 

Keep up the good work!

**Comment by shurcooL** [comment]
I'm not sure what you're referring to with `GLFWExperimental`. These bindings are generated using `glow` and do not use `glew`.

I will close this issue since your original problem has been resolved. But feel free to reply or reopen issue if needed.

**Comment by sharpner** [comment]
yep thx. You helped me a lot.

**Comment by allochi** [comment]
Hi, 

I'm trying to follow a C++ OpenGL tutorial. It draws a white triangle in the middle of a window, without using any shaders. When I port the code to Golang, I get a blank window. when I use the shaders from the code above, the triangle shows up.

Do I have to use shaders with go-gl?

**Comment by shurcooL** [comment]
@allochi, I recommend looking at the go-gl examples repo:

https://github.com/go-gl/examples

It contains two examples. One uses OpenGL 4.1 Core and shaders to render a cube.

The other uses OpenGL 2.1 and immediate mode rendering, no shaders, to render a cube.

Both should be go-gettable, see their corresponding README.

> Do I have to use shaders with go-gl?

That's not a very specific question. I assume you mean with some of the go-gl/gl bindings. As shown above, no, you don't always have to use shaders. You can also use the legacy immediate mode.

**Comment by allochi** [comment]
@shurcooL Thanks Dmitri.

I'm quite new to OpenGL, so I don't know about immediate mode (yet), and I guess my questions could sound weird :D

I did study the examples and the code above, and I already added basic shaders to my tutorial code, and it works now. It's just looked strange to me that I ported the C++ code line by line to golang, yet I didn't get the same result.

Thanks again!

**Comment by shurcooL** [comment]
It's very easy to make a mistake in one of the many lines, which would cause things to fail.

I suggest you post the exact code somewhere and ask this question on Slack (or IRC) in #go-gl or some OpenGL-related channel. Also, there are many good resources for learning OpenGL. I highly suggest looking at some.

Immediate mode is legacy. It's easier to work with, but it's much more inefficient and unsupported in modern OpenGL versions (and in OpenGL ES 2.0 and WebGL).
