### ISSUE TITLE
Runtime panic with Go 1.6 (due to new cgo pointer rules)

### ISSUE THREAD

**Issue by aliasaila** [go-gl/gl#31]
This [commit](https://github.com/golang/go/commit/9dcc58c3d139ee0475fdaca8119812c014ec5ba1) checks pointers passed from Go to C.

An example of the resulting panic:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
github.com/go-gl/gl/v3.2-compatibility/gl.ShaderSource(0x100000004, 0xc820028108, 0x0)
	src/github.com/go-gl/gl/v3.2-compatibility/gl/package.go:25551 +0x4c
```

**Comment by shurcooL** [comment]
Thanks for reporting. This is an issue we knew would come up eventually, and it looks like we'll need to address it by 1.6.

See https://github.com/golang/go/issues/12416 for relevant change.

**Comment by shurcooL** [comment]
Also see https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md.

**Comment by shurcooL** [comment]
@slimsag and I have looked into a possible fix for this, and I think we've come up with a workable solution.

**Comment by shurcooL** [comment]
I've created PR #44 that aims to try to resolve this issue. It needs review, so anyone interested, feel free to take a look, perhaps even try it with your code.

**Comment by shurcooL** [comment]
This has been resolved. Please see https://github.com/go-gl/examples/pull/52/files for example usage.
