### ISSUE TITLE
glActiveTexture error when gl.Init()

### ISSUE THREAD

**Issue by WideMod** [go-gl/gl#33]
panic: glActiveTexture

goroutine 1 [running, locked to thread]:
main.main()
	(my project path)/(my go file name).go:16 +0x50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_386.s:1662 +0x1

I'm using Windows 10, Intel HD4000 Graphic card.
I don't know why this problem occurs.

**Comment by shurcooL** [comment]
Are you able to build and run one of the OpenGL samples? For example, this one:

https://github.com/go-gl/examples/tree/master/glfw31-gl21-cube

**Comment by WideMod** [comment]
Yes I can.
But my project makes error

source:
package main

import (
    "runtime"
    "github.com/go-gl/gl/v3.3-core/gl"
)

func init() {
    runtime.LockOSThread()
}

func main() {
	if err := gl.Init(); err != nil {
            panic(err)
        }
}

**Comment by shurcooL** [comment]
That is not valid code. You need to call `gl.Init()` **after** you've created an OpenGL context and _made it current_.

I know there's a platform difference between OS X/Linux and Windows here, in that the above (invalid) program will not produce an error on OS X and Linux, but it will on Windows.

Try the following code instead:

```Go
func main() {
	if err := glfw.Init(); err != nil {
		log.Fatalln("failed to initialize glfw:", err)
	}
	defer glfw.Terminate()

	window, err := glfw.CreateWindow(640, 480, "Title", nil, nil)
	if err != nil {
		panic(err)
	}
	window.MakeContextCurrent() // Now that the context has been made current, you can call gl.Init().

	if err := gl.Init(); err != nil {
		log.Fatalln("failed to initialize gl bindings:", err)
	}

	version := gl.GoStr(gl.GetString(gl.VERSION))
	fmt.Println("OpenGL version", version)
}
```

You can also try the OpenGL 4.1 sample at https://github.com/go-gl/examples/tree/master/glfw31-gl41core-cube.

**Comment by shurcooL** [comment]
Let me know if that fixes it for you.

If so, we need to update the README's [Usage section](https://github.com/go-gl/gl#usage), because it suggests the wrong thing.

**Comment by shurcooL** [comment]
@WideMod, can you confirm if that fixed your problem?

I'm pretty sure the current README is incorrect and we need to update it.

**Comment by shurcooL** [comment]
Ping @WideMod.

**Comment by shurcooL** [comment]
I'm pretty confident the above is true. Sadly, the original issue poster didn't confirm. But we've gone ahead and made the adjustments to `gl.Init` docs and README, so hopefully this doesn't happen to other people in the future.
