### ISSUE TITLE
Shader gives black screen [2.1]

### ISSUE THREAD

**Issue by gdm85** [go-gl/gl#35]
I am trying to use shaders with OpenGL 2.1 and getting only a black screen, foreword: I am not very familiar with shaders in general; is there an example available for go-gl? Would it be useful to add one via PR? No errors are returned by the GL layer by the way.

I will submit a minimal testcase soon; the cube example works fine even when called from within my program, but everything is black once I use a simple GL program+shader.

By the way, I wonder why [apitrace](https://github.com/apitrace/apitrace) does not parse the calls...is there any other tracing tool that could be used to inspect the frames? I have tried gDEBugger without success.

**Comment by shurcooL** [comment]
> is there an example available for go-gl?

Yes, please see [go-gl/examples](https://github.com/go-gl/examples/blob/master/glfw31-gl41core-cube).

**Comment by gdm85** [comment]
@shurcooL oh I noticed that one, however as it specifies version 4.1 I thought it wouldn't be a proper 2.1 example too.

**Comment by shurcooL** [comment]
Sorry, I missed the specific OpenGL version in your phrase "trying to use shaders with OpenGL 2.1".

I don't think it'd be hard to change the OpenGL 4.1 example with shaders to use OpenGL 2.1 (with extensions), it doesn't do anything uncommon.

You can also try one of my OpenGL 2.1 projects that uses shaders, for example, https://github.com/shurcooL/Hover.

**Comment by gdm85** [comment]
@shurcooL nice! Thanks for the pointers; I think my main issue was that I was not properly using `BufferData` and unfortunately there is no compile-time errors on that.

I have found out that apitrace 7.1 can correctly give me all calls in frames, so now I am well armed.
