### ISSUE TITLE
gl_v3.3-core output:undefined: gl.LoadIdentity

### ISSUE THREAD

**Issue by godispy** [go-gl/gl#36]
import  "github.com/go-gl/gl/all-core/gl"
is ok!

than

import  "github.com/go-gl/gl/v3.3-core/gl"	
output:undefined: gl.LoadIdentity
why?? how to fix it?

**Comment by godispy** [comment]
I works on linux

**Comment by tapir** [comment]
glLoadIdentity does not exist in OpenGL Core 3.3
