### ISSUE TITLE
conversions helper addition: ptrWithOffset

### ISSUE THREAD

**Issue by tanema** [go-gl/gl#39]
Hey All,

I have a proposal for a helper in the conversions. There is a helper I have created to get an offset starting point in an array when passing an attrib pointer that looks like this

```golang
func ptrWithOffset(data interface{}, offset int) unsafe.Pointer {
	return unsafe.Pointer(uintptr(gl.Ptr(data)) + uintptr(offset))
}
```

and I use it like this:

```golang
gl.VertexAttribPointer(0, 2, gl.FLOAT, false, 4*4, gl.Ptr(coords))
gl.VertexAttribPointer(1, 2, gl.FLOAT, false, 4*4, ptrWithOffset(coords, 2*4))
```

I thought it would be a useful addition to the package.

cheers!

**Comment by Jragonmiris** [comment]
Why not just use Ptr(&array[index])?

**Comment by tanema** [comment]
because I had not thought of that? thanks that clears up a bit of my code

**Comment by Jragonmiris** [comment]
Sorry if my terse phrasing came off as rude. I was phone typing. Glad it
helped.
