### ISSUE TITLE
Runtime panic with Go 1.6

### ISSUE THREAD

**Issue by tbogdala** [go-gl/gl#43]
Go 1.6 introduces new runtime checks with cgo which causes panics in the generated GL wrappers. An example of a code that causes this (from the v3.3-core wrapper) is:

````
    func ShaderSource(shader uint32, count int32, xstring **uint8, length *int32) {
        C.glowShaderSource(
            gpShaderSource, 
            (C.GLuint)(shader), 
            (C.GLsizei)(count), 
            (**C.GLchar)(unsafe.Pointer(xstring)),  
            (*C.GLint)(unsafe.Pointer(length)))
    }
````

That now gets detected at runtime:

```
    panic: runtime error: cgo argument has Go pointer to Go pointer
```

This is a reference to the Go issue that's relevant:
https://github.com/golang/go/issues/12416

**Comment by shurcooL** [comment]
Thanks for reporting. We're already tracking this in #31. There should be a fix within a few days.

**Comment by tbogdala** [comment]
Whoops! Sorry about that.
