### ISSUE TITLE
Conservative rasterization 

### ISSUE THREAD

**Issue by acterhd** [go-gl/gl#55]
Hello. I can't found conservative rasterization on Go language. Where I can found? Have  go opengl CR or not?

**Comment by pwaller** [comment]
Hi, I'm afraid I'm not aware of one, and you haven't provided any references for the sort of thing you're looking for. I'm afraid this might not be the best venue to ask your question - you might get better help on https://stackoverflow.com.

**Comment by acterhd** [comment]
I tried rebuild go-gl, and add extension of conservative rasterization.
