### ISSUE TITLE
Compiler warnings: passing const char pointer

### ISSUE THREAD

**Issue by EtienneBruines** [go-gl/gl#56]
Using `go version devel +f8fc371 Thu Apr 21 17:04:01 2016 +0000 linux/amd64`, when compiling something that uses `gl`:

``` go
# github.com/go-gl/gl/v2.1/gl
../../go-gl/gl/v2.1/gl/procaddr.go:54:28: warning: passing 'const char *' to parameter of type 'const GLubyte *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
/usr/include/GL/glx.h:325:48: note: passing argument to parameter 'procname' here
```

Even though `go tip` might change a lot, the error message seems legit.

**Comment by shurcooL** [comment]
That looks like a valid warning about const-correctness. Thanks for reporting.

We should fix it to be const-correct and avoid the warning.

As far as I can tell, this applies to Linux, so whoever has an easier time testing the fix on Linux can take this.

**Comment by pwaller** [comment]
I don't currently see this warning. If you do, please ping the thread and I'll reopen, or file a new issue, thanks!
