### ISSUE TITLE
glh and glu

### ISSUE THREAD

**Issue by zzz125** [go-gl/gl#6]
will they work with the new opengl wrapper?
currently they use old (and also seems broken) imports

**Comment by pwaller** [comment]
Yes, these are stale, sadly. I will try and take a look this evening to see how hard it is to fix them. Any help is welcomed.

**Comment by jteeuwen** [comment]
Not sure if much of the stuff in there is still relevant.

**Comment by pwaller** [comment]
It's a fair point. Probably they should just be moved to go-gl-legacy and have their imports updated.

**Comment by shurcooL** [comment]
I'm in favor of doing that.

**Comment by pwaller** [comment]
I've moved them.

**Comment by shurcooL** [comment]
Thanks!

As a result, https://github.com/go-gl looks a little cleaner and more readable now! :tada:

**Comment by pwaller** [comment]
:)
