### ISSUE TITLE
Lack of extensions in the core profile

### ISSUE THREAD

**Issue by dv343** [go-gl/gl#61]
I don't know if this is a proper bug or just a documentation problem.

I was trying to use anisotropic filtering with EXT_texture_filter_anisotropic, but the core profile didn't contain the required constant (TEXTURE_MAX_ANISOTROPY_EXT). The compability profile has it, but I prefer to stick with the core profile.

Is the lack of this constant a bug? If not, why it has been removed from the core profile (as far as I know this is not deprecated)?

Thanks

**Comment by shurcooL** [comment]
Which package are you referring to? Which OpenGL version?

The OpenGL bindings are generated via [go-gl/glow](https://github.com/go-gl/glow#readme), so it's unlikely a human error on our side. It's either not a problem and the mistake is on your side, or there's an issue in one of the XML files being used for generation.

**Comment by dv343** [comment]
I'm using version 4.1 (core profile): "github.com/go-gl/gl/v4.1-core/gl". If this is my mistake, then gl.TEXTURE_MAX_ANISOTROPY_EXT is not on the 4.1-core as expected, right? I'll try to generate my own 4.1-core bindings using glow and see if that works.

**Comment by dv343** [comment]
I followed glow Readme to generate my own bindings and the result is the same as this. I'll report this to them.
