### ISSUE TITLE
WebGL Question

### ISSUE THREAD

**Issue by 4ydx** [go-gl/gl#62]
Are any of the go-gl/gl packages compatible with webgl? Looking at gopherjs/webgl, it seems to me that there probably isn't a simple way to get go-gl to interact with webgl.  Am I correct about that?

**Comment by shurcooL** [comment]
> Are any of the go-gl/gl packages compatible with webgl?

There is. Please see https://github.com/goxjs/gl.

**Comment by 4ydx** [comment]
Much appreciated.
