### ISSUE TITLE
Where is gl.Texture and gl.GLenum?

### ISSUE THREAD

**Issue by prsolucoes** [go-gl/gl#63]
Hi,

With a very old version i have:
**gl.Texture and gl.GLenum**

But after update today, it doesnt exists more :(

What i need change? Can you give some directions?

I got the samples from here:
https://github.com/vova616/GarageEngine/blob/master/engine/Texture.go

Thanks.

**Comment by shurcooL** [comment]
> I got the samples from here:
> https://github.com/vova616/GarageEngine/blob/master/engine/Texture.go

That code is indeed very old. It refers to a `gl` package that has been deprecated. It's still available at http://github.com/go-gl-legacy/gl.

However, I'd strongly encourage you to look at the current OpenGL bindings available in this repo:

https://godoc.org/github.com/go-gl/gl

You can find examples at [https://github.com/go-gl/examples](https://github.com/go-gl/examples#readme).

**Comment by errcw** [comment]
(Closing because the question was answered.)
