### ISSUE TITLE
TexStorageXD should only be available in 4.2+

### ISSUE THREAD

**Issue by FlorianUekermann** [go-gl/gl#64]
Some or all of the TexStorageXD functions should only be available in OpenGL 4.2+.
I saw them in the 3.3 package. I didn't check any details (versions and which functions exactly).

**Comment by shurcooL** [comment]
Are you sure they wouldn't be available via extensions?

**Comment by MaVo159** [comment]
Not sure at all. But in core that shouldn't matter right?

**Comment by shurcooL** [comment]
`TexStorage2D` is available even in 2.1 bindings:

https://godoc.org/github.com/go-gl/gl/v2.1/gl#TexStorage2D

I think it's because it might be accessible in a 2.1–4.1 context via `ARB_texture_storage` extension. Is that right @errcw?

**Comment by shurcooL** [comment]
Yeah, if you look at [`glow` generator](https://github.com/go-gl/glow) docs, one of the flags is:

> `addext`: A regular expression describing which extensions to include. .* by default, including everything.

We're using the default, so all extensions get added.

So I don't think this is an issue or a bug, it's working as expected. If you want to generate your own 4.1-core bindings without additional extensions, you'll need to generate them with `glow` with `addext` flag set to match nothing. Hopefully @errcw can confirm this.

**Comment by shurcooL** [comment]
I believe there's no bug here, so I'll close this to keep the list of open issues more actionable. Please feel free to leave comments or reopen otherwise.
