### ISSUE TITLE
Using bindings on Windows 10?

### ISSUE THREAD

**Issue by Kapho** [go-gl/gl#65]
I can't seem to use these bindings on Windows. I've tried reinstalling MinGW, but there seems to be an error with the C compiler. Could anyone help me out?
```

C:\Users\default.DESKTOP-I2M9C05>go get -u github.com/go-gl/gl/v3.3-core/gl
# github.com/go-gl/gl/v3.3-core/gl
realgcc.exe: fatal error: no input files
compilation terminated.
```

**Comment by Kapho** [comment]
oops i'm an idiot. After realizing I was using Haskell's gcc, I installed 64-bit minGW and got it working.

**Comment by shurcooL** [comment]
Glad to hear that. I wasn't able to offer help because I don't use Windows.
