### ISSUE TITLE
Retrieve Uniform or Attribute name

### ISSUE THREAD

**Issue by raedatoui** [go-gl/gl#67]
I am trying to retrieve the info of attributes and uniforms of an already linked shader.
The shader is working and the calls `gl.GetActiveAttrib` and `gl.GetActiveUniform` are working as expected.
I am just stuck on converting the uint8 type to a Go string
```
var count int32
var i uint32
var s, b, l int32
var t uint32
var n uint8

gl.GetProgramiv(program, gl.ACTIVE_UNIFORMS, &count)
fmt.Printf("Active Uniforms: %d\n", count)
for i = 0; i < uint32(count); i++ {
	gl.GetActiveUniform(program, i, b, &l, &s, &t, &n)
	fmt.Println(i, b, l, s, t,  gl.GoStr(&n))
}
```
`gl.GoStr(&n)` is returning an empty string. How can I properly convert n to a string?
much appreciated!

**Comment by shurcooL** [comment]
You're not using the OpenGL call properly. Read its documentation:

http://docs.gl/gl2/glGetActiveUniform

Specifically:

- bufSize - Specifies the maximum number of characters OpenGL is allowed to write in the character buffer indicated by name.
- length - Returns the number of characters actually written by OpenGL in the string indicated by name (excluding the null terminator) if a value other than NULL is passed.

You're currently passing it a bufSize value of 0, so of course emptry string is all it can give you.

Look at the example at the bottom of that documentation page. It uses a buffer of size 256. Try that.

**Comment by raedatoui** [comment]
oh doh! thank you for you and your patience
