### ISSUE TITLE
gl.GetAttribLocation and gl.EnableVertexAttribArray types

### ISSUE THREAD

**Issue by raedatoui** [go-gl/gl#68]
Why does `gl.GetAttribLocation` return an int32 for an attribute's location but `gl.EnableVertexAttribArray` and `gl.VertexAttribPointer` expect uint32?

**Comment by shurcooL** [comment]
That's how it is in the OpenGL specification:

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetAttribLocation.xhtml - returns `GLint`.
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnableVertexAttribArray.xhtml - takes `GLuint`.
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml - takes `GLuint`.
