### ISSUE TITLE
MultMatrixd

### ISSUE THREAD

**Issue by zzz125** [go-gl/gl#7]
how can i use new MultMatrixd?

new function looks like this:
```go
func MultMatrixd(m *float64) {
	C.glowMultMatrixd(gpMultMatrixd, (*C.GLdouble)(unsafe.Pointer(m)))
}
```
here "m *float64" is a poiner to single float, but i need to pass [16]float64{...} to it like in the old wrapper.

i cant figure it, the only thing i can pass is either single float64 (wrong), or array/pointer to array of 16 floats (won't compile)

i also tried to pass gl.Ptr(&arr) without success, there are no any code with this function in new repo too

should "m *float64" be some kind of raw bytes (like string) or something? was it even tested / is usable?

thx

**Comment by zzz125** [comment]
also example of old code (works with old wrapper)   
```go
mf := []float64{m[0][0], m[0][1], m[0][2], m[0][3],
                      m[1][0], m[1][1], m[1][2], m[1][3],
                      m[2][0], m[2][1], m[2][2], m[2][3],
                      m[3][0], m[3][1], m[3][2], m[3][3]}

gl.MultMatrixd(&mf)
```

**Comment by jteeuwen** [comment]
Try `gl.MultMatrixd(&mf[0])`

**Comment by zzz125** [comment]
yes it works with &mf[0]

thank you
