### ISSUE TITLE
Error creating window on OS X 10.12.5

### ISSUE THREAD

**Issue by dobegor** [go-gl/gl#79]
Hi!

When creating window using `win, err := window.New("glfw", 800, 600, "Hello G3N", false)` it returns an error:

```VersionUnavailable: NSGL: The targeted version of OS X only supports forward-compatible contexts for OpenGL 3.2 and above```

I am using v3.3-core, and I assume 3.3 is above 3.2 and this error is kind of strange.

Any way to fix this?

**Comment by shurcooL** [comment]
> v3.3-core

Do you mean you're importing that package? Did set actually set those hints before creating window?

See https://github.com/go-gl/example/blob/ee0644b7c5650555db3c0f4d04f9ef5716e6c6ac/gl41core-cube/cube.go#L39-L42 for example.

**Comment by drgomesp** [comment]
I have the same exact issue.

**Comment by shurcooL** [comment]
Does the [cube example ](https://github.com/go-gl/example/tree/master/gl41core-cube) work for you?

**Comment by dobegor** [comment]
@shurcooL 
Sorry, I referred to GL erroneously, I meant GLFW 3.2.
Adding this to initialization sequence:
```
glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)
```
helped to launch correctly.

However, there are some other rendering glitches on macOS, which don't happen on Windows/Linux.
Please, see this issue for details: https://github.com/g3n/engine/issues/19

**Comment by cjburkey01** [comment]
Here, use these window hints:
```
glfw.WindowHint(glfw.ContextVersionMajor, 3)
glfw.WindowHint(glfw.ContextVersionMinor, 3)
glfw.WindowHint(glfw.Resizable, glfw.True)
glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCoreProfile)
glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)
```
It's a GLFW + Mac thing, happens with LWJGL too.

**Comment by errcw** [comment]
(Closing from inactivity, hopefully the last comment resolved.)
