### ISSUE TITLE
v3.1/gles2: Not supported on macOS.

### ISSUE THREAD

**Issue by ynaoto** [go-gl/gl#87]
```
$ go get -u github.com/go-gl/gl/v3.1/gles2
# github.com/go-gl/gl/v3.1/gles2
go/src/github.com/go-gl/gl/v3.1/gles2/package.go:37:11: fatal error: 'KHR/khrplatform.h' file not found
 #include <KHR/khrplatform.h>
          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by errcw** [comment]
I don't believe macOS supports GLES?

**Comment by shurcooL** [comment]
As far as I know, it does not. If you have evidence otherwise, please let us know.

https://developer.apple.com/opengl/ mentions only macOS.

https://developer.apple.com/opengl-es/ mentions only iOS and tvOS (not macOS).

**Comment by errcw** [comment]
I believe this question is resolved.
