### ISSUE TITLE
OpenGL 4.6 support

### ISSUE THREAD

**Issue by kjozic** [go-gl/gl#88]
When can we expect support for OpenGL 4.6?

**Comment by errcw** [comment]
It should be straightforward to generate the new bindings. I'll try and make time this week to do it.

**Comment by errcw** [comment]
It should be straightforward to generate the new bindings. I'll try and make time this week to do it.

**Comment by kjozic** [comment]
When I try to generate the new bindings using glow (glow generate -out=./v4.6-core/gl/ -api=gl -version=4.6 -profile=core -xml=../glow/xml/) following error occurs: 
```2017/11/05 12:32:03 unable to generate package: &{gl 4.6 core /home/kreso/golang/src/github.com/go-gl/glow/tmpl <nil> <nil> false}```

**Comment by shurcooL** [comment]
That error happens on this line:

https://github.com/go-gl/glow/blob/75d9c6716e5939e941a3fc5e2d6afaf36f52514d/main.go#L123

If it happens, that means `spec.HasPackage(packageSpec)` was not true for any of the specs in the XML directory.

**Comment by shurcooL** [comment]
It looks like we need to update the contents of the [XML directory](https://github.com/go-gl/glow/tree/master/xml) with the latest XML specifications. The ones currently there now only have 4.5, not 4.6.

@errcw Is it documented anywhere how to update the contents of the XML directory? I can't find it (not in the README of the repo, nor in the README within the `xml` directory, not in wiki).

**Comment by shurcooL** [comment]
Now that https://github.com/go-gl/glow/issues/90 is resolved, we can proceed here.

**Comment by shurcooL** [comment]
I've created PR #92 that'll resolve this issue.
