### ISSUE TITLE
gl.GenBuffers not accepting uint32 array?

### ISSUE THREAD

**Issue by tehcyx** [go-gl/gl#99]
Hi,

I'm trying to initialize multiple buffers in one call, passing an array to the GenBuffers function, is this not possible in the port or am I just doing something wrong?

```
const (
	POSITION_VB int = 0
	TEXCOORD_VB int = 1
	NORMAL_VB   int = 2
	INDEX_VB    int = 3
	NUM_BUFFERS int = 4
)

type Mesh struct {
	vao uint32              // vertex array object
	vbo [NUM_BUFFERS]uint32 // vertex buffer object
}

gl.GenBuffers(int32(NUM_BUFFERS), &m.vbo)
```

resulting in error:
> cannot use &m.vbo (type *[4]uint32) as type *uint32 in argument to gl.GenBuffers

I've been doing this successfully in C.

**Comment by shurcooL** [comment]
I think it should be possible. Since the parameter type is `*uint32`, you'll need to take address of the first element of the array rather than the entire array:

```Go
gl.GenBuffers(int32(NUM_BUFFERS), &m.vbo[0])
```

**Comment by tehcyx** [comment]
Well, you're right. That got rid of the error. I'll see that it works as well, as soon as I finish up that mesh generation.
